### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alldne** [alldne/dotfiles#1]
- [x] tmux
- [ ] install scripts (install nvm, go etc)
- [x] copy/paste in tmux
- [x] color for tmux
- [x] consider https://github.com/robbyrussell/oh-my-zsh
- [ ] neovim
